### ISSUE TITLE
Comment: State ini.options_present found in sls mysql is unavailable

### ISSUE THREAD

**Issue by arthurzenika** [CSSCorp/openstack-automation#10]
I believe s/ini/ini_manage/

Has ini_manage been integrated in salt ? http://docs.saltstack.com/en/latest/ref/states/all/salt.states.ini_manage.html If so, maybe it could be removed from _modules to avoid code duplication ?

**Comment by Akilesh1597** [comment]
I do not see it with version 0.17.5. What version are you using?

**Comment by arthurzenika** [comment]
This is a new convention with 2014.1, I believe it won't impact 0.17.x but we should make sure.

**Comment by Akilesh1597** [comment]
ini_manage not yet integrated into salt modules officially packages. at least for a few distros. So this has to wait for now.
