### ISSUE TITLE
Support for icehouse installation

### ISSUE THREAD

**Issue by arthurzenika** [CSSCorp/openstack-automation#15]
Do you have any plans to support an icehouse  (next version of havana) installation ?

**Comment by Akilesh1597** [comment]
Please check icehouse-yaml branch. The states for icehouse are working and
have done a few installations using it. However as I have made some changes
you might encounter minor issues. Please report back and I'll get it sorted
out immediately.

Thank you,
Ageeleshwar K

**Comment by arthurzenika** [comment]
Great stuff, thanks for the tip, I'm taking a look at the branch as we speak.

**Comment by Akilesh1597** [comment]
Meanwhile icehouse-yaml was tested on Ubuntu 14.04. I believe that if you use any other version you might have to add the icehouse repo manually to sources.list.
