### ISSUE TITLE
I want to talk about CSSCorps/openstack-automation repo at OSCON

### ISSUE THREAD

**Issue by EntropyWorks** [CSSCorp/openstack-automation#17]
I'm working on my slides for OSCON http://www.oscon.com/oscon2014/ and would love to promote this repo and the developers working on it.  Would that be ok with CSSCorp? Have a logo or other info I can add. 

Thanks, Yazz

**Comment by samof76** [comment]
Hey Yazz.

We are not sure if our company would eventually allow the logo, but it would great if you could just mention us, and also please share the video link of the presentation that you give.

Thanks,
Sam
