### ISSUE TITLE
have example pillars in the repo so pillars aren't tracked by git

### ISSUE THREAD

**Issue by arthurzenika** [CSSCorp/openstack-automation#22]
Openstack_Icehouse/pillar/openstack_cluster.sls and Openstack_Icehouse/pillar/openstack_cluster_inverse.sls could be moved to .example files and then .gitignore could include these files. In the README you would instruct to copy both these files and then edit them.

**Comment by Akilesh1597** [comment]
First of all sorry for delayed response. Any rationale behind this approach? The reason I ask it I have split up the pillar definition into multiple files now. The only part of the pillar that any user would not want to change is cluster_resources.sls. All other pillar sls files would be common for a basic install. The user can however add more customized options.  

But all these can be done by forking the repo. and pull requests will be accepted only for files in file_roots directory and not pillar_roots. Further now that the repo need not be cloned to your local disk for installation. Installation can be done by using gitfs as bakend. So my question is 'Is this issue still credible?'

**Comment by Akilesh1597** [comment]
Please make sure that you create a new branch after you fork say 'dev'. Inside dev do not make changes to any files in 'pillar_root'. That way you can pull request with only changes made to file_root.

In your other branches you can make any changes to your pillar data.
