### ISSUE TITLE
implement cinder deployment

### ISSUE THREAD

**Issue by arthurzenika** [CSSCorp/openstack-automation#23]
I see there are empty cinder.sls any plans on implementing this ? 

I might give it a shot soon.

**Comment by Akilesh1597** [comment]
I have got lots of pending work on this repo. Will start working on them soon.

**Comment by Akilesh1597** [comment]
Check https://github.com/Akilesh1597/salt-openstack. Or wait untill it reaches here. 
The way I am implementing cinder is
1. Check for any free space in disk. If available create a lvm partition and use it as cinder backend.
