### ISSUE TITLE
Provide documentation to use with gitfs

### ISSUE THREAD

**Issue by arthurzenika** [CSSCorp/openstack-automation#24]
Hopefully one can use gitfs http://salt.readthedocs.org/en/v2014.1.4/topics/tutorials/gitfs.html?highlight=gitfs to use these pillars and states, it would be nice to document how to set it up (if possible).

**Comment by Akilesh1597** [comment]
Setting up gitfs is not so tough. Infact there is a much bigger project
here https://github.com/saltstack-formulas. To add to that saltstack is
adding support for paremeterizing pillar data. Once that is done anyone
wishing to install openstack only need to point to our repo from their
master then just provide values for the parameters defined in our pillar
and can have a private cloud as per their needs.

I have plans for these and will update the repo soon, hopefully aligned
with the juno release of openstack.

**Comment by Akilesh1597** [comment]
Please check https://github.com/Akilesh1597/salt-openstack. The files there would eventually be merged here after development is complete. I am closing this issue as of now, even though the activity is still not complete.
