### ISSUE TITLE
Add a single node nova.conf state file.

### ISSUE THREAD

**Issue by fivethreeo** [CSSCorp/openstack-automation#26]
Something like nova.controller_compute_combined so nova can be removed in controller pillar and nova.compute_kvm can be replaced by nova.controller_compute_combined in compute pillar.

**Comment by Akilesh1597** [comment]
This does not matter. The states in the two files will not affect each other.

**Comment by fivethreeo** [comment]
Even if run on the same minion?

On 5 November 2014 15:37, Akilesh1597 notifications@github.com wrote:

> This does not matter. The states in the two files will not affect each
> other.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CSSCorp/openstack-automation/issues/26#issuecomment-61815655
> .

## 

Øyvind Saltvik

**Comment by Akilesh1597** [comment]
Yes. Even when run on same node. They each will install their respective packages, update options files with their required options and restart their respective services. I see no reason why one would affect the other. I am planning a single machine install today for testing. Will confirm after that.

**Comment by Akilesh1597** [comment]
tested, everything fine here.
