### ISSUE TITLE
No License on this Project

### ISSUE THREAD

**Issue by 0xf10e** [CSSCorp/openstack-automation#43]
Hi there,

you're stating nowhere what's the license on this project. Not even 
"this is licensed under the same term's as (OpenStack||SaltStack)" 
(which would be Apache Public License in both cases).

As far as I know this means it's "All Rights reserved" as this is the 
default under most jurisdictions and this is probably not what's
intended here.

Regards, Florian

PS: I took a quick look on your neutron-module but I guess I can't
use it until the license is clear.

**Comment by naviens** [comment]
Added License
