### ISSUE TITLE
Why JSON?

### ISSUE THREAD

**Issue by EntropyWorks** [CSSCorp/openstack-automation#5]
Why did you decide to write salt states in JSON / Jinja format? 

JSON doesn't allow for comments and such. Its really not a great choice for configuration files that a human has to edit.

**Comment by Akilesh1597** [comment]
It allows me to visualise what arguments would be passed to the state modules. Any ways I agree with you. the Json files can easily be converted to yaml if user desires. I could write a small script to do so.

**Comment by fivethreeo** [comment]
Got a fork with yaml here: https://github.com/fivethreeo/openstack-automation

But using icehouse instead of havana

**Comment by Akilesh1597** [comment]
Will create a new branch for icehouse with both yaml and json format shortly with support to configure ml2

**Comment by fivethreeo** [comment]
Almost have icehouse working in my repo, but got some issues with networking could really need some help.

Akilesh could really use your help.

**Comment by Akilesh1597** [comment]
Sure I am a network guy originally. What is the problem with networking
that you are facing? If you can wait a couple of days I am about to push
formulas for ml2 and ovs plugin. Also for the entire ice house stack.

**Comment by fivethreeo** [comment]
I get Failed to bind port fd47e6af-9578-4898-9f0f-f0e99ca673b3 on host saltvikprime, maybe your ml2 formula will fix it.

**Comment by Akilesh1597** [comment]
I am almost done with my formulas. I also ran into the same error as yours.
I saw this bug 'https://bugs.launchpad.net/neutron/+bug/1244255'.

in /etc/neutron/neutron.conf
[Default]
agent_down_time = 75
[agent]
report_interval = 30

I set the below in '/etc/nova/nova.conf'

[Default]
                        "vif_plugging_is_fatal": "False",
                        "vif_plugging_timeout": "0"

I restarted all services related to neutron and nova I have my instance
running. Now I have another issue at hand. I am unable to ping or ssh.
hopefully I can find and fix it by tomorrow.

Meanwhile if you need the ml2 formula alone find in the attached file. Also
attached is the pillar file I am using.

**Comment by Akilesh1597** [comment]
json formulas for icehouse are available in a separate branch now. yaml shall be updated soon.

**Comment by UtahDave** [comment]
+1 for yaml 

:)

**Comment by Akilesh1597** [comment]
Yaml formulas are available.

**Comment by UtahDave** [comment]
awesome! Thanks!
