### ISSUE TITLE
Running everything on one physical server

### ISSUE THREAD

**Issue by fivethreeo** [CSSCorp/openstack-automation#6]
I would like to run everything one one server with just a eth0 interface.

I run into three issues:
1. nova.conf in nova.compute_kvm conflicts with the one in nova.init
2. wich pillar should i use for net when i only have a eth0
3. the way i tried, the net it goes down and i have to log in without net and remove the bridges before i can reach the physical server again.

Any tips? :)

**Comment by Akilesh1597** [comment]
The formulas will not work for you. I would have to write a new formula for single machine install. 
As of now you can allow the formulas to run and fail. Now do some faking as below.

ovs-vsctl add-br br-eth0
ovs-vsctl add-port br-eth0 eth0
ifconfig br-eth0 <eth0's ip address> up
ip link set br-eth0 promisc on
ip link add proxy-br-eth1 type veth peer name eth1-br-proxy
ip link add proxy-br-ex type veth peer name ex-br-proxy
ovs-vsctl add-br br-eth1
ovs-vsctl add-br br-ex
ovs-vsctl add-port br-eth1 eth1-br-proxy
ovs-vsctl add-port br-ex eth1-br-proxy
ovs-vsctl add-port br-eth0 proxy-br-eth1
ovs-vsctl add-port br-eth0 proxy-br-ex
ip link set eth1-br-proxy up promisc on
ip link set ex-br-proxy up promisc on
ip link set proxy-br-eth1 up promisc on
ip link set proxy-br-ex up promisc on

What we have done is added a new bridge br-eth0 and added eth0 to it.
Assign eth0's ip address to br-eth0 and set the interface in promiscous mode.
Then we create two veth pairs. In case you are not aware they are like virtual cables.
We connect br-eth1 and br-ex to br-eth0 using the veth pairs.
Then we enable promiscous mode and bring up all the interfaces we use

Try it and tell me if it works. I'll add a formula for it.

**Comment by fivethreeo** [comment]
This seems to work but in horizon i get this:

Error: Failed to launch instance "one": Please try again later [Error: Authentication required].

**Comment by Akilesh1597** [comment]
This means your keystone is not set up correct. I have vastly changed many
formulas can you please get a new copy from git and run state.high state
again.

**Comment by Akilesh1597** [comment]
Closing this issue as no update... Please reopen if you face any problems again with latest state files.
