### ISSUE TITLE
Are these states actually being used?

### ISSUE THREAD

**Issue by UtahDave** [CSSCorp/openstack-automation#8]
Are these states actually being used? I was able to get this working, but there were several sls errors that I had to fix.

**Comment by UtahDave** [comment]
I'm using the icehouse yaml branch.  Would pull requests against that branch be welcome?

**Comment by UtahDave** [comment]
https://github.com/CSSCorp/openstack-automation/pull/9   fixes the errors I was seeing

**Comment by Akilesh1597** [comment]
Merged your request. Actually 
-    - require: 
-      - module: create_init_bridges
  can be removed completely as I had moved the logic to neutron.ml2.

Also we no longer need to care about '/etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini' unless we are not using ml2 at all. 

I'll make these chages
